name: Update Gaming Library

on:
  schedule:
    - cron: '20 22 * * *'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Close GitHub Repository
        uses: actions/checkout@v4

      - name: Setup Ruby Environment
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Execute
        run: bundle exec ruby run.rb
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
          STEAM_EXCLUDE_GAME_IDS: ${{ secrets.STEAM_EXCLUDE_GAME_IDS }}
